# docker-compose.yml
version: "3.9"

services:
  code:
    build:
      context: .
      args:
        - DEV=true
    image: khajaghar-api:1.0
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

