# docker-compose.yml
version: "3.9"

services:
  code:
    build:
      context: .
      args:
        - DEV=true
    image: khajaghar-api:1.0
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:17.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=changeme
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: